name: Waka Readme

on:
  schedule:
    - cron: '30 18 * * *' # 한국 시간 기준 자정 (UTC 15:30)
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        env:
          SHOW_TIMEZONE: True
          SHOW_LANGUAGE: True
          SHOW_OS: True
          SHOW_LINES_OF_CODE: False
          SHOW_PROJECTS: False
          SHOW_EDITORS: False
          SHOW_LOC_CHART: False
          SHOW_PROFILE_VIEWS: False
          SHOW_COMMIT: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_SHORT_INFO: False
          IGNORED_REPOS: False
          SYMBOL_VERSION: 1
          DEBUG_LOGGING: False
