name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
    # cron: '00 15 * * *'로 하면 한국 시간 기준으로 오전 12:00에 업데이트 된다
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        env:
          SHOW_COMMIT: False
          SHOW_PROJECTS: False
          SHOW_EDITORS: False
          SHOW_LOC_CHART: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_SHORT_INFO: False
          SHOW_PROFILE_VIEWS: False
          IGNORED_REPOS: False
          SYMBOL_VERSION: 1
          DEBUG_LOGGING: False
